language: node_js
node_js:
    - "7"
cache:
  directories:
    - node_modules
script: 
    - npm test
    - npm run cover
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
